[bitcoin]
addresses_to_fund = [
    "bcrt1qmj7zctm6kduqaaqust8jxs0rhau5j65ysw9n74", # Ledger account 0
    "bcrt1qjnmexntp6z9tm4ywj5j7pmrlfxh83e68l9puk6", # Ledger account 1
    "bcrt1qc252m6afz9v5mfpjpulr92gm7ywgdhkxtlv9xr"
]

[ethereum]
addresses_to_fund = [
    "0x5087fb5F19f8EF0585b4EFcb3375De97C9d0fE0e", # Ledger account 0
    "0xeD56BBA7d30FEb908aB7a5a7b3b16654cb45a38C", # Ledger account 1
    "0x05c40cfe76bc2bee261be51493378c24f2c96ae9"
]
