name: Package

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]
        # os: [macos-latest, windows-2019, ubuntu-18.04]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 13

      - name: yarn install
        run: |
          yarn install

      - name: yarn lint
        run: |
          yarn lint
          yarn tsc

      - name: yarn test
        run: |
          yarn test

      - name: Run E2E test
        uses: GabrielBB/xvfb-action@v1.2
        with:
          working-directory: ./ #optional
          run: |
            yarn build-e2e
            yarn test-e2e

      - name: yarn package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn package

      - name: Check directory
        run: |
          ls
          ls release

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-app
          path: release
# Failing because virtual framebuffer not installed
#          yarn build-e2e
#          yarn test-e2e
