name: Package

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]
        # os: [macos-latest, windows-2019, ubuntu-18.04]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 13

      - name: yarn install
        run: |
          yarn install

      - name: yarn lint
        run: |
          yarn lint
          yarn tsc

      - name: yarn package
        run: |
          yarn package

      - name: Check directory
        run: |
          ls
          ls release

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.os }}
          path: release
# Failing because virtual framebuffer not installed
#          yarn build-e2e
#          yarn test-e2e
