name: Test

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]
        # os: [macos-latest, ubuntu-18.04]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 13

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Echo default symlink (1.0.2)
        run: |
          ls -l /usr/local/opt | grep openssl

      - name: Echo openssl path
        run: |
          echo $(brew --prefix openssl)/include

      - name: Symlink to openssl 1.1
        run: |
          sudo ln -s /usr/local/opt/openssl $(brew --prefix openssl)

      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     env LDFLAGS="-L$(brew --prefix openssl)/lib" CFLAGS="-I$(brew --prefix openssl)/include" pip install cryptography

      - name: Echo default symlink
        run: |
          ls -l /usr/local/opt | grep openssl

      - name: yarn install
        run: |
          yarn install

      - name: yarn test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn package-ci
          yarn lint
          yarn tsc

# Failing because virtual framebuffer not installed
#          yarn build-e2e
#          yarn test-e2e
